spring.application.name=movie-watchlist

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_watchlist_db
spring.datasource.username=ramadhanial-qadri
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never

app.jwt.secret=movie-watchlist-super-secret-key-for-hmac-sha256-authentication
app.jwt.expiration=86400000
